=== canadianavalancheassociation/caaml-bulletin-eaws/6.0/CAAMLv6_BulletinEAWS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://caaml.org/Schemas/V6.0/Profiles/BulletinEAWS"
		xmlns:caaml="http://caaml.org/Schemas/V6.0/Profiles/BulletinEAWS"
		xmlns:gml="http://www.opengis.net/gml/3.2"
		version="6.0.0"
		elementFormDefault="qualified">
	<import namespace="http://www.opengis.net/gml/3.2" schemaLocation="gml/3.2.2/gml.xsd"/>

	<!--**********************************************************-->
	<!--***         OBSERVATION COLLECTION ELEMENTS            ***-->
	<!--**********************************************************-->
	<element name="bulletins" type="caaml:BulletinsType"/>
	<complexType name="BulletinsType">
		<sequence>
			<element name="bulletin" type="caaml:BulletinType" maxOccurs="unbounded"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
	</complexType>

	<!--**********************************************************-->
	<!--***                 BULLETIN ELEMENTS                  ***-->
	<!--**********************************************************-->
	<element name="bulletin" type="caaml:BulletinType"/>
	<complexType name="BulletinType" final="#all">
		<sequence>
			<element name="publicationTime" type="dateTime"/>
			<element name="validTime" type="caaml:ValidTimeType"/>
			<element name="source" type="caaml:SourceType"/>
			<element name="region" type="caaml:RegionType" maxOccurs="unbounded"/>
			<element name="dangerRating" type="caaml:DangerRatingType" maxOccurs="unbounded"/>
			<element name="avalancheProblem" type="caaml:AvalancheProblemType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="highlights" type="string" minOccurs="0"/>
			<element name="wxSynopsis" type="caaml:TextsBaseType" minOccurs="0"/>
			<element name="avalancheActivity" type="caaml:TextsBaseType" minOccurs="0"/>
			<element name="snowpackStructure" type="caaml:TextsBaseType" minOccurs="0"/>
			<element name="travelAdvisory" type="caaml:TextsBaseType" minOccurs="0"/>
			<element name="tendency" type="caaml:TendencyType" minOccurs="0"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
		<attribute name="bulletinID" type="string" use="required"/>
		<attribute name="lang" type="language" use="required"/>
	</complexType>

	<!--**********************************************************-->
	<!--***              DANGER RATING ELEMENTS                ***-->
	<!--**********************************************************-->
	<complexType name="DangerRatingType">
		<sequence>
			<element name="mainValue" type="caaml:DangerRatingValueType"/>
			<element name="elevation" type="caaml:ElevationType" minOccurs="0"/>
			<element name="validTimePeriod" type="caaml:ValidTimePeriodType" minOccurs="0"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
	</complexType>
	<simpleType name="DangerRatingValueType">
		<restriction base="string">
			<enumeration value="low"/>
			<enumeration value="moderate"/>
			<enumeration value="considerable"/>
			<enumeration value="high"/>
			<enumeration value="very_high"/>
			<enumeration value="no_snow"/>
			<enumeration value="no_rating"/>
		</restriction>
	</simpleType>

	<!--**********************************************************-->
	<!--***           AVALANCHE PROBLEM ELEMENTS               ***-->
	<!--**********************************************************-->
	<complexType name="AvalancheProblemType">
		<sequence>
			<element name="problemType" type="caaml:AvalancheProblemTypeType"/>
			<element name="elevation" type="caaml:ElevationType" minOccurs="0"/>
			<element name="aspect" type="caaml:AspectType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="validTimePeriod" type="caaml:ValidTimePeriodType" minOccurs="0"/>
			<element name="terrainFeature" type="string" minOccurs="0"/>
			<element name="avalancheSize" type="caaml:AvalancheSizeType" minOccurs="0"/>
			<element name="snowpackStability" type="caaml:SnowpackStabilityType" minOccurs="0"/>
			<element name="frequency" type="caaml:FrequencyType" minOccurs="0"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
	</complexType>
	<simpleType name="AvalancheProblemTypeType">
		<restriction base="string">
			<enumeration value="new_snow"/>
			<enumeration value="wind_drifted_snow"/>
			<enumeration value="persistent_weak_layers"/>
			<enumeration value="wet_snow"/>
			<enumeration value="gliding_snow"/>
			<enumeration value="cornice_failure"/>
			<enumeration value="favourable_situation"/>
		</restriction>
	</simpleType>
	<simpleType name="AvalancheSizeType">
		<restriction base="integer">
			<minInclusive value="1"/>
			<maxInclusive value="5"/>
		</restriction>
	</simpleType>
	<simpleType name="SnowpackStabilityType">
		<restriction base="string">
			<enumeration value="very_poor"/>
			<enumeration value="poor"/>
			<enumeration value="fair"/>
			<enumeration value="good"/>
		</restriction>
	</simpleType>
	<simpleType name="FrequencyType">
		<restriction base="string">
			<enumeration value="few"/>
			<enumeration value="some"/>
			<enumeration value="many"/>
		</restriction>
	</simpleType>

	<!--**********************************************************-->
	<!--***                 TENDENCY ELEMENTS                  ***-->
	<!--**********************************************************-->
	<complexType name="TendencyType">
		<complexContent>
			<extension base="caaml:TextsBaseType">
				<sequence>
					<element name="tendencyType" type="caaml:TendencyTypeType"/>
					<element name="validTime" type="caaml:ValidTimeType" minOccurs="0"/>
					<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
					<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<simpleType name="TendencyTypeType">
		<restriction base="string">
			<enumeration value="decreasing"/>
			<enumeration value="steady"/>
			<enumeration value="increasing"/>
		</restriction>
	</simpleType>

	<!--**********************************************************-->
	<!--***                 META DATA ELEMENTS                 ***-->
	<!--**********************************************************-->
	<complexType name="MetaDataType">
		<sequence>
			<element name="extFile" type="caaml:ExtFileType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="comment" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	<!-- EXTERNAL FILES -->
	<complexType name="ExtFileType">
		<sequence>
			<element name="fileType" type="string" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
			<element name="fileReferenceURI" type="anyURI"/>
		</sequence>
	</complexType>
	<!-- CUSTOM DATA-->
	<complexType name="CustomDataType" final="#all">
		<sequence>
			<any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<!--**********************************************************-->
	<!--***                  SOURCE ELEMENTS                   ***-->
	<!--**********************************************************-->
	<complexType name="SourceType">
		<choice>
			<element name="provider" type="caaml:ProviderType"/>
			<element name="person" type="caaml:PersonType"/>
		</choice>
	</complexType>
	<!--  PROVIDER  -->
	<complexType name="ProviderType" final="#all">
		<complexContent>
			<extension base="caaml:SourceBaseType">
				<sequence>
					<element name="contactPerson" type="caaml:PersonType" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<!--  PERSON  -->
	<complexType name="PersonType" final="#all">
		<complexContent>
			<extension base="caaml:SourceBaseType"/>
		</complexContent>
	</complexType>
	<complexType name="SourceBaseType">
		<sequence>
			<element name="name" type="string"/>
			<element name="website" type="anyURI" minOccurs="0"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
	</complexType>

	<!--**********************************************************-->
	<!--***                 LOCATION ELEMENTS                  ***-->
	<!--**********************************************************-->
	<!-- LOCATION -->
	<complexType name="RegionType" final="#all">
		<sequence>
			<element name="name" type="string"/>
			<element name="centerPoint" type="gml:PointType" minOccurs="0"/>
			<element name="outline" type="gml:PolygonType" minOccurs="0"/>
			<element name="metaData" type="caaml:MetaDataType" minOccurs="0"/>
			<element name="customData" type="caaml:CustomDataType" minOccurs="0"/>
		</sequence>
		<attribute name="regionId" type="string" use="required"/>
	</complexType>
	<!-- ASPECT -->
	<simpleType name="AspectType">
		<restriction base="string">
			<enumeration value="N"/>
			<enumeration value="NE"/>
			<enumeration value="E"/>
			<enumeration value="SE"/>
			<enumeration value="S"/>
			<enumeration value="SW"/>
			<enumeration value="W"/>
			<enumeration value="NW"/>
			<enumeration value="n/a"/>
		</restriction>
	</simpleType>
	<!-- ELEVATION -->
	<complexType name="ElevationType" final="#all">
		<sequence>
			<element name="lowerBound" type="caaml:ElevationBaseType" minOccurs="0"/>
			<element name="upperBound" type="caaml:ElevationBaseType" minOccurs="0"/>
		</sequence>
		<attribute name="uom" type="string" use="required" fixed="m"/>
	</complexType>
	<simpleType name="ElevationBaseType">
		<restriction base="string">
			<pattern value="treeline|0|[1-9][0-9]*[0][0]+"/>
		</restriction>
	</simpleType>

	<!--**********************************************************-->
	<!--***                 TIME ELEMENTS                      ***-->
	<!--**********************************************************-->
	<complexType name="ValidTimeType" final="#all">
		<sequence>
			<element name="startTime" type="dateTime"/>
			<element name="endTime" type="dateTime"/>
		</sequence>
	</complexType>
	<simpleType name="ValidTimePeriodType">
		<restriction base="string">
			<enumeration value="all_day"/>
			<enumeration value="earlier"/>
			<enumeration value="later"/>
		</restriction>
	</simpleType>

	<!--**********************************************************-->
	<!--***                 TEXTS ELEMENTS                      ***-->
	<!--**********************************************************-->
	<complexType name="TextsBaseType">
		<sequence>
			<element name="highlights" type="string" minOccurs="0"/>
			<element name="comment" type="string" minOccurs="0"/>
		</sequence>
	</complexType>

</schema>

=== canadianavalancheassociation/caaml-bulletin-eaws/6.0/examples/2019-01-16_avalanche_report_en.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<bulletins xmlns="http://caaml.org/Schemas/V6.0/Profiles/BulletinEAWS" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://caaml.org/Schemas/V6.0/Profiles/BulletinEAWS http://caaml.org/Schemas/V6.0/Profiles/BulletinEAWS/CAAMLv6_BulletinEAWS.xsd">
  <metaData>
    <extFile>
      <type>link</type>
      <description>Link to the website</description>
      <fileReferenceURI>https://avalanche.report/bulletin/2019-01-16</fileReferenceURI>
    </extFile>
    <extFile>
      <type>simple_link</type>
      <description>Link to the simplified website</description>
      <fileReferenceURI>https://avalanche.report/simple/2019-01-16/en.html</fileReferenceURI>
    </extFile>
    <extFile>
      <type>fd_albina_map.jpg</type>
      <description>Danger rating map (whole day)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/fd_albina_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>fd_tyrol_map.jpg</type>
      <description>Danger rating map Tirol (whole day)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/fd_tyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>fd_southtyrol_map.jpg</type>
      <description>Danger rating map Southtyrol (whole day)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/fd_southtyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>fd_trentino_map.jpg</type>
      <description>Danger rating map Trentino (whole day)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/fd_trentino_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pdf</type>
      <description>PDF </description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/2019-01-16_en.pdf</fileReferenceURI>
    </extFile>
    <extFile>
      <type>tyrol_pdf</type>
      <description>PDF Tirol </description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/2019-01-16_AT-07_en.pdf</fileReferenceURI>
    </extFile>
    <extFile>
      <type>southtyrol_pdf</type>
      <description>PDF Southtyrol </description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/2019-01-16_IT-32_BZen.pdf</fileReferenceURI>
    </extFile>
    <extFile>
      <type>trentino_pdf</type>
      <description>PDF Trentino </description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/2019-01-16_IT-32-TN_en.pdf</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_albina_map.jpg</type>
      <description>Danger rating map (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_albina_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_tyrol_map.jpg</type>
      <description>Danger rating map Tirol (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_tyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_southtyrol_map.jpg</type>
      <description>Danger rating map Southtyrol (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_southtyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_trentino_map.jpg</type>
      <description>Danger rating map Trentino (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_trentino_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_albina_map.jpg</type>
      <description>Danger rating map (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_albina_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_tyrol_map.jpg</type>
      <description>Danger rating map Tirol (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_tyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_southtyrol_map.jpg</type>
      <description>Danger rating map Southtyrol (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_southtyrol_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_trentino_map.jpg</type>
      <description>Danger rating map Trentino (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_trentino_map.jpg</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_overlay.png</type>
      <description>Danger rating overlay (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_overlay.png</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_overlay.png</type>
      <description>Danger rating overlay (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_overlay.png</fileReferenceURI>
    </extFile>
    <extFile>
      <type>am_regions.json</type>
      <description>GeoJSON for regions (AM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/am_regions.json</fileReferenceURI>
    </extFile>
    <extFile>
      <type>pm_regions.json</type>
      <description>GeoJSON for regions (PM)</description>
      <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/pm_regions.json</fileReferenceURI>
    </extFile>
  </metaData>
  <bulletin id="ID_a19bd3dc-85df-448f-be5e-f88f0c14ed4f" lang="en">
    <metaData>
      <extFile>
        <type>dangerRatingMap</type>
        <description>Simplified danger rating map of the region</description>
        <fileReferenceURI>https://avalanche.report/albina_files_local/2019-01-16/2019-01-15_16-00-00/a19bd3dc-85df-448f-be5e-f88f0c14ed4f.jpg</fileReferenceURI>
      </extFile>
      <extFile>
        <type>website</type>
        <description>Link to region on the website</description>
        <fileReferenceURI>https://avalanche.report/bulletin/2019-01-16?region=a19bd3dc-85df-448f-be5e-f88f0c14ed4f</fileReferenceURI>
      </extFile>
    </metaData>
    <publicationTime>2019-01-15T16:00:00Z</publicationTime>
    <validTime>
      <startTime>2019-01-15T23:00:00Z</startTime>
      <endTime>2019-01-16T11:00:00Z</endTime>
    </validTime>
    <source>
      <operation>
        <name>Avalanche.report</name>
        <website>https://avalanche.report/</website>
      </operation>
    </source>
    <region id="IT-32-BZ-07">
      <name>Texel Mountains</name>
    </region>
    <region id="IT-32-BZ-11">
      <name>Durreck Range</name>
    </region>
    <region id="IT-32-BZ-12">
      <name>Western Rieserferner Mountains</name>
    </region>
    <region id="IT-32-BZ-01">
      <name>Val MÃ¼stair Alps</name>
    </region>
    <region id="IT-32-BZ-02">
      <name>Langtaufers</name>
    </region>
    <region id="IT-32-BZ-03">
      <name>Schnals Ridge</name>
    </region>
    <region id="IT-32-BZ-04">
      <name>Southern Stubai Alps</name>
    </region>
    <region id="IT-32-BZ-05">
      <name>Southern Zillertal Alps and High Tauern</name>
    </region>
    <complexity>easy</complexity>
    <dangerRating>
      <mainValue>considerable</mainValue>
      <elevation uom="m">
        <lowerBound>1600</lowerBound>
      </elevation>
    </dangerRating>
    <dangerRating>
      <mainValue>considerable</mainValue>
      <elevation uom="m">
        <upperBound>1600</upperBound>
      </elevation>
    </dangerRating>
    <avalancheProblem>
      <type>new_snow</type>
      <aspect>S</aspect>
      <aspect>SW</aspect>
      <aspect>W</aspect>
      <aspect>NW</aspect>
      <aspect>NE</aspect>
      <aspect>SE</aspect>
      <aspect>E</aspect>
      <aspect>N</aspect>
      <terrainFeature> Many starting zones have released the snow but not entirely.</terrainFeature>
      <matrixInformation>
        <artificialDangerRating>considerable</artificialDangerRating>
        <artificialAvalancheSize>3</artificialAvalancheSize>
        <artificialAvalancheReleaseProbability>3</artificialAvalancheReleaseProbability>
        <artificialHazardSiteDistribution>2</artificialHazardSiteDistribution>
        <naturalDangerRating>moderate</naturalDangerRating>
        <naturalAvalancheReleaseProbability>2</naturalAvalancheReleaseProbability>
        <naturalHazardSiteDistribution>1</naturalHazardSiteDistribution>
      </matrixInformation>
    </avalancheProblem>
    <avalancheProblem>
      <type>wind_drifted_snow</type>
      <aspect>S</aspect>
      <aspect>SW</aspect>
      <aspect>W</aspect>
      <aspect>NW</aspect>
      <aspect>NE</aspect>
      <aspect>SE</aspect>
      <aspect>E</aspect>
      <aspect>N</aspect>
      <matrixInformation>
        <artificialDangerRating>considerable</artificialDangerRating>
        <artificialAvalancheSize>3</artificialAvalancheSize>
        <artificialAvalancheReleaseProbability>3</artificialAvalancheReleaseProbability>
        <artificialHazardSiteDistribution>2</artificialHazardSiteDistribution>
        <naturalDangerRating>moderate</naturalDangerRating>
        <naturalAvalancheReleaseProbability>2</naturalAvalancheReleaseProbability>
        <naturalHazardSiteDistribution>1</naturalHazardSiteDistribution>
      </matrixInformation>
    </avalancheProblem>
    <tendency>
      <type>decreasing</type>
      <validTime>
